{% set version = "2.3.1" %}

package:
  name: soupsieve
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/soupsieve/soupsieve-{{ version }}.tar.gz
  sha256: b8d49b1cd4f037c7082a9683dfa1801aa2597fb11c3a1155b7a5b94829b4f1f9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  requires:
    - beautifulsoup4
  imports:
    - soupsieve

about:
  home: http://facelessuser.github.io/soupsieve
  license: MIT
  license_file: LICENSE.md
  summary: A modern CSS selector implementation for BeautifulSoup

extra:
  recipe-maintainers:
    - jschueller
